<a href="https://colab.research.google.com/github/Sujal261/journey/blob/main/00_firstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)



2.5.0+cu121


In [ ]:
#creating tensor first so we can learn machine learning
scalar= torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:

#to get the scalar from the tensor
scalar.item()

7

In [ ]:
#now we are learning for the vector
vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape
#this givrs the no. of elemrnts

torch.Size([2])

In [ ]:
Matrix = torch.tensor([[7,7],
 [4,4]])
Matrix

tensor([[7, 7],
        [4, 4]])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
TENSOR= torch.tensor([[[1,2,3],
                     [2,3,4],
                     [5,6,7]]])
TENSOR.ndim

3

In [ ]:
TENSOR.shape
#here one is there it says there is one 3 by 3 matrix
#it says like there is one 3by 3 matrix in one big bracjet

torch.Size([1, 3, 3])

##random tensors
how does it work in neural network at first it starts with random numbers then it adjusts and it updates again it looks at data and it updates this way it updates the tensors



In [ ]:
#creating a randopm tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3445, 0.2106, 0.6335, 0.6834],
        [0.0086, 0.5949, 0.3619, 0.9389],
        [0.9891, 0.1032, 0.1715, 0.8622]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_image_tensor=torch.rand(size=(3,224,224))
#here three represnets colour channels of imaghes and 224 224 reepresenrs the height
#and width of image
random_image_tensor.ndim

3

Zeros and ones

In [ ]:
#creating tensor with all zeros
zeros= torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#creasting range
one_to_ten = torch.arange(start = 1 , end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zers= torch.zeros_like(input = one_to_ten)
ten_zers

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
one_to_ten.shape

torch.Size([10])

In [ ]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0],
                               dtype=None,
                               device=None,
                              requires_grad=False )
float_32_tensor

tensor([3., 4., 5.])

tensor daatatypes is one od the 3 big error we will run into with pytorch and deeep learning
1. tensors not right data typw
tensors nt right shaoe
tensots not on the right device  

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
int_32_tensor = torch.tensor([3, 4, 5], dtype=torch.long)
int_32_tensor


tensor([3, 4, 5])

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 16., 25.])

Tensors not  right datatype- to check this we can wrote tensor.dtype
for right shape- tensor.shape
for right device- tensor.device

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3156, 0.2530, 0.4800, 0.1738],
        [0.2120, 0.6089, 0.6031, 0.0061],
        [0.8584, 0.3815, 0.2498, 0.2823]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3156, 0.2530, 0.4800, 0.1738],
        [0.2120, 0.6089, 0.6031, 0.0061],
        [0.8584, 0.3815, 0.2498, 0.2823]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manipulating tensors
tensors opersationsinclude:
Addition
subtraction
multiplication
division
matric multiplication   

In [ ]:
tensor = torch.tensor([2,4,4])
tensor + 10

tensor([12, 14, 14])

In [ ]:
tensor = tensor * 10
tensor

tensor([20, 40, 40])

In [ ]:
##matrix multiplication
torch.matmul(tensor, tensor)

tensor(3600)

In [ ]:
##element wise matrix multiplication
print(f"value = {tensor * tensor}")


value = tensor([ 400, 1600, 1600])


In [ ]:
%%time
value=0
for i in range (len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(3600)
CPU times: user 1.44 ms, sys: 0 ns, total: 1.44 ms
Wall time: 1.46 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 110 µs, sys: 0 ns, total: 110 µs
Wall time: 114 µs


tensor(3600)

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.5323, 0.5482, 0.2298],
        [0.3663, 0.4161, 0.1279],
        [0.3899, 0.4285, 0.1475]])

In [ ]:
tensor_A=torch.tensor([[1,2],
           [3,4],
           [5,6]])
tensor_B =torch.tensor ([[5,6],
           [3,9],
           [8,6]])
# torch.matmul(tensor_A, tensor_B)
tensor_B.shape

torch.Size([3, 2])

In [ ]:
tensor_B = tensor_B.T
tensor_B.shape

torch.Size([2, 3])

In [ ]:
torch.matmul(tensor_A, tensor_B)

tensor([[17, 21, 20],
        [39, 45, 48],
        [61, 69, 76]])

In [ ]:
x= torch.arange(0 ,100 ,10 )
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), torch.max(x)

(tensor(0), tensor(90))

In [ ]:
torch.mean(x)
#here it shows error becausse mean is caluclated in particular data typr in pytorvh

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.dtype

torch.int64

In [ ]:
#thios shows there wee should take care of data typw while using pytorch

In [ ]:
#argmin is used to fins the positional indec where minimum vaue is locates
x.argmin()

tensor(0)

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.sum()


tensor(450)

In [ ]:
x.argmax()
##here 9 gives the indec where maximum vakue is placed

tensor(9)

we are attanging our tensor in desried shape

In [ ]:
x= torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_resshaped = x.reshape([1,8])
x_resshaped
##here error is due to not maching shApes in reshape and given tensor
##here if we do reshape agaon with same shaPE AS input then extra dimension will be added

RuntimeError: shape '[1, 8]' is invalid for input of size 9

In [ ]:
x_rs=x.reshape([9,1])
x_rs

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
#Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:, 0]=4
z, x

(tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
## here remember that usign view we can so same work as reshape but while reshaping it doesnot
##share the mempry but while using view we sharfe the memory

we talkimg stac now

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked


tensor([[4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.],
        [4., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#squeeze- it removwes all single dimension form the tensor
x_rs

tensor([[4.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
x_rs.shape
print(f"Previous tensor:{x_rs}")
print(f"Previous shape:{x_rs.shape}")

x_squeezed = x_rs.squeeze()
print(f"Squeezed tensor:{x_squeezed}")
print(f"after squeezed tenpsr:{x_squeezed.shape}")

Previous tensor:tensor([[4.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape:torch.Size([9, 1])
Squeezed tensor:tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.])
after squeezed tenpsr:torch.Size([9])


In [ ]:
x_rs.squeeze().shape

torch.Size([9])

In [ ]:
#unsqueeze this add a single dimension to a target tensor
print(f"Previous target:{x_squeezed}")
print(f"Previous shape:{x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\n New tensor :{x_unsqueezed}")
print(f"New shape :{x_unsqueezed.shape}")

Previous target:tensor([4., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape:torch.Size([9])

 New tensor :tensor([[4.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape :torch.Size([9, 1])


In [ ]:
#permute - it rearranges the tensor to the target dimension provided
x_original = torch.rand(size = (224,224,3))
#we can permute this original tensor to arrange the axis
x_permuted = x_original.permute(2,0,1)

print(f"Previous shape :{x_original.shape}")
print(f"New permutted shape:{x_permuted.shape}")

Previous shape :torch.Size([224, 224, 3])
New permutted shape:torch.Size([3, 224, 224])


In [ ]:
tensor1=torch.arange(1,13)
tensor1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
tensor_rs=tensor1.reshape([3,4])
tensor_rs

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [ ]:
tensor_x=torch.tensor([7,8,9])
tensor_y=torch.tensor([10,11,12])
tensor_stack= torch.stack((tensor_x, tensor_y), dim=1)
tensor_stack


tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_5= torch.randn(1,4,1,5)
tensor_5


tensor([[[[-1.1340, -0.3629, -0.5511,  0.0945,  1.2723]],

         [[ 0.3526,  0.0113,  0.1226,  1.2803,  1.1691]],

         [[-0.1385, -1.3794, -1.1471, -0.7883,  0.6415]],

         [[ 1.1892, -1.4964, -0.4062,  1.1202, -0.4446]]]])

In [ ]:
tensor_squeeze= tensor_5.squeeze()
tensor_squeeze.shape

torch.Size([4, 5])

#indexing(selectinfg data from form tensors)


In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]#here it is talking about the first dimension and whole tensor lies in inde 0 so whole will be printed

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]#here the after selecting whole it goes to next dimension and it slects the 0 th position within it so 1,2,3 is orinted

tensor([1, 2, 3])

In [ ]:
x[0][0][0]#here inisde 1,2,3 1 lies in 0th place so 1 is the ouryput

tensor(1)

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,0,0]

tensor([1])

In [ ]:
x[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
x[:,0,:]

tensor([[1, 2, 3]])

In [ ]:
x[:,2,2]

tensor([9])

In [ ]:
x[:,:,2]

tensor([[3, 6, 9]])

###Pyorch tensors and numpy
if the data are in numpy we change it into pytorch tensors using torch.from_numpy(ndarray)

pytorch tensor -. numoy-. torch.Tensor.numpy()

In [ ]:
import numpy as np

In [ ]:
array= np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor.dtype

AttributeError: module 'torch' has no attribute 'view'

Remeber that default data type of torch tensor is float 32 and default data type of numpy is float 64

In [ ]:
array = array+1
array, tensor
#here see that changing the arrat doesnot change the tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#converting tensor to numpy
tensor= torch.ones(7)
numpyy = tensor.numpy()
tensor, numpyy

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#here we cans see thatr data typer of numpy array is float32
numpyy.dtype

dtype('float32')

In [ ]:
tensor = tensor+1
tensor, numpyy
#here changng the tensor doesnot change the numpy arrya

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###reproducibitly (trying to take random out of random)

in short hoe a neural network learns???
it startsd with random numbers and tensors operations and update random numbers that represents the data and this processs continues until ir correctly represents rhe data in pytorch we to reduce the randomnness in neural networks pytorch comes with the concept of random seed

it adds flavour to the randomness

In [ ]:
import torch
radom_tensor1 = torch.rand(3,3)
random_tensor2 = torch.rand(3,3)
print(radom_tensor1)
print(random_tensor2)

tensor([[0.3926, 0.0928, 0.4618],
        [0.0260, 0.5625, 0.5441],
        [0.6226, 0.3561, 0.3793]])
tensor([[0.3326, 0.7900, 0.9934],
        [0.1857, 0.4576, 0.9677],
        [0.0975, 0.4610, 0.9905]])


In [ ]:
torch.rand(3,3)

tensor([[0.1202, 0.5030, 0.8757],
        [0.3677, 0.5458, 0.1615],
        [0.1336, 0.5265, 0.1236]])

In [ ]:
random_seed = 42
torch.manual_seed(random_seed)
random_tensora = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensorb = torch.rand(3,4)

print(random_tensora == random_tensorb)
random_tensora, random_tensorb


#here keep in mind that if we are using the manual seed then it will work only for ther block of code

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

#running tensors and pytorch obkects on the gpus
gpus= fater computation on numbers
how to get gpus
1. use for free usaing google colab
2. using own gpu
3. use cloud computing like gcp, aws, azure there are the cloud computing platform

In [ ]:
!nvidia-smi

Fri Nov  8 14:25:39 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
#check for gpu access with pytorch
import torch
torch.cuda.is_available()

True

In [2]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Moving tensor to CPU

In [ ]:
#IF A TENSOR IS ON GPU IT CANNOT BE TRANSFORMED IT TO NUMPY
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
back_to_cpu = tensor_on_gpu.cpu().numpy()
back_to_cpu

array([1, 2, 3])

In [ ]:
random_seed=0
torch.manual_seed(random_seed)
tensor_a=torch.rand(size=(7,7))
print(tensor_a)
torch.manual_seed(random_seed)
tensor_b= torch.rand(1,7)
tensor_c =torch.matmul(tensor_b, tensor_b.T)
print(tensor_b)
print(tensor_b.T)
tensor_c

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])


tensor([[1.5985]])

In [ ]:

tensor_b= torch.rand(1,7)
tensor_c =torch.matmul(tensor_b, tensor_b.T)
print(tensor_b)
print(tensor_b.T)
tensor_c

tensor([[0.8770, 0.4682, 0.9788, 0.0791, 0.9267, 0.1111, 0.8949]])
tensor([[0.8770],
        [0.4682],
        [0.9788],
        [0.0791],
        [0.9267],
        [0.1111],
        [0.8949]])


tensor([[3.6244]])

In [4]:
import torch
torch.manual_seed(1234)
tensor= torch.rand(2,3)
tensor_a=tensor.to(device)
tensor_a

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [9]:
tensor_b= tensor_a.reshape(3,2)
tensor_c=torch.matmul(tensor_a, tensor_b)
tensor_c

tensor([[0.1204, 0.3411],
        [0.0666, 0.6596]], device='cuda:0')

In [11]:
tensor_c.min(), tensor.max()

(tensor(0.0666, device='cuda:0'), tensor(0.7006))

In [12]:
tensor_c.argmin(), tensor_c.argmax()

(tensor(2, device='cuda:0'), tensor(3, device='cuda:0'))

In [13]:
random_seed=7
torch.manual_seed(random_seed)
tensor1= torch.rand(1,1,1,10)
print(f"first tensor{tensor1}")
print(f"fist tensors shape {tensor1.shape}")

tensor2= tensor1.squeeze()
print(f"first tensor{tensor2}")
print(f"fist tensors shape {tensor2.shape}")



first tensortensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
fist tensors shape torch.Size([1, 1, 1, 10])
first tensortensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
fist tensors shape torch.Size([10])
